// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.3
// source: prot_bee_body_map.proto

package protbee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResMapThumbnails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumbnails []*Thumbnail `protobuf:"bytes,1,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
}

func (x *ResMapThumbnails) Reset() {
	*x = ResMapThumbnails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prot_bee_body_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMapThumbnails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMapThumbnails) ProtoMessage() {}

func (x *ResMapThumbnails) ProtoReflect() protoreflect.Message {
	mi := &file_prot_bee_body_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMapThumbnails.ProtoReflect.Descriptor instead.
func (*ResMapThumbnails) Descriptor() ([]byte, []int) {
	return file_prot_bee_body_map_proto_rawDescGZIP(), []int{0}
}

func (x *ResMapThumbnails) GetThumbnails() []*Thumbnail {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

var File_prot_bee_body_map_proto protoreflect.FileDescriptor

var file_prot_bee_body_map_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x5f, 0x62, 0x65, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f,
	0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x62,
	0x65, 0x65, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x5f, 0x62, 0x65, 0x65, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x4d, 0x61,
	0x70, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x62, 0x65, 0x65, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x52, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x42,
	0x26, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x62, 0x65, 0x65, 0x2e, 0x70, 0x62, 0x66, 0x48, 0x03,
	0x5a, 0x15, 0x7a, 0x6b, 0x2d, 0x61, 0x74, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x70, 0x62, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x62, 0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prot_bee_body_map_proto_rawDescOnce sync.Once
	file_prot_bee_body_map_proto_rawDescData = file_prot_bee_body_map_proto_rawDesc
)

func file_prot_bee_body_map_proto_rawDescGZIP() []byte {
	file_prot_bee_body_map_proto_rawDescOnce.Do(func() {
		file_prot_bee_body_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_prot_bee_body_map_proto_rawDescData)
	})
	return file_prot_bee_body_map_proto_rawDescData
}

var file_prot_bee_body_map_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prot_bee_body_map_proto_goTypes = []interface{}{
	(*ResMapThumbnails)(nil), // 0: protbee.ResMapThumbnails
	(*Thumbnail)(nil),        // 1: protbee.Thumbnail
}
var file_prot_bee_body_map_proto_depIdxs = []int32{
	1, // 0: protbee.ResMapThumbnails.thumbnails:type_name -> protbee.Thumbnail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prot_bee_body_map_proto_init() }
func file_prot_bee_body_map_proto_init() {
	if File_prot_bee_body_map_proto != nil {
		return
	}
	file_prot_bee_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_prot_bee_body_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMapThumbnails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prot_bee_body_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prot_bee_body_map_proto_goTypes,
		DependencyIndexes: file_prot_bee_body_map_proto_depIdxs,
		MessageInfos:      file_prot_bee_body_map_proto_msgTypes,
	}.Build()
	File_prot_bee_body_map_proto = out.File
	file_prot_bee_body_map_proto_rawDesc = nil
	file_prot_bee_body_map_proto_goTypes = nil
	file_prot_bee_body_map_proto_depIdxs = nil
}
